=== Machina123/XmlProcessing/lab7/04_catalog.dtd
<!ELEMENT CATALOG (PRODUCT+)>
<!ELEMENT PRODUCT (SPECIFICATIONS+, OPTIONS?, PRICE+, NOTES?)>
<!ELEMENT SPECIFICATIONS (#PCDATA)>
<!ELEMENT OPTIONS (#PCDATA)>
<!ELEMENT PRICE (#PCDATA)>
<!ELEMENT NOTES (#PCDATA)>

<!ATTLIST SPECIFICATIONS WEIGHT CDATA #IMPLIED>
<!ATTLIST OPTIONS FINISH (Metal | Matte) "Matte">
<!ATTLIST OPTIONS CASE (HardShell | Soft | NotApplicable) "HardShell">
<!ATTLIST PRICE CURRENCY CDATA "USD">
<!ATTLIST PRICE SHIPPING CDATA #IMPLIED>

=== Machina123/XmlProcessing/lab7/04_catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Importowanie zewnÄ™trznego DTD -->
<!DOCTYPE CATALOG SYSTEM "04_catalog.dtd">
<CATALOG>
    <PRODUCT>
        <SPECIFICATIONS WEIGHT="10">My spec #1</SPECIFICATIONS>
        <SPECIFICATIONS>My spec #2</SPECIFICATIONS>
        <OPTIONS FINISH="Matte" CASE="NotApplicable">My options</OPTIONS>
        <PRICE CURRENCY="USD">1000</PRICE>
    </PRODUCT>

    <PRODUCT>
        <SPECIFICATIONS WEIGHT="100">Second product spec #1</SPECIFICATIONS>
        <OPTIONS FINISH="Metal" CASE="HardShell">Options numero duo</OPTIONS>
        <PRICE CURRENCY="USD">2500</PRICE>
        <PRICE CURRENCY="USD" SHIPPING="yes">2650</PRICE>
        <NOTES>Deliver ASAP</NOTES>
    </PRODUCT>
</CATALOG>
